FROM python:slim

# Update package list and install necessary packages in one layer
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    git \
    mosquitto-clients \
    ruby \
    ruby-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/* \
    && gem install asciidoctor asciidoctor-pdf

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . ./app/

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]